resourcechanges 
|extend targetResourceId = tostring(properties.targetResourceId), changeType = tostring(properties.changeType), createTime = todatetime(properties.changeAttributes.timestamp) 
| where createTime > ago(7d) and changeType == "Create" or changeType == "Update" or changeType == "Delete"
| project  targetResourceId, changeType, createTime 
| join ( Resources | extend targetResourceId=id) on targetResourceId
| where tags ['ServiceOwner'] =~ 'CloudPlatformTeam' 
| order by createTime desc 
| project createTime, id, resourceGroup, type